# Generated by Django 3.2.15 on 2022-12-06 12:38

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, verbose_name='имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='фамилия')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='номер телефона')),
                ('address', models.CharField(max_length=255, verbose_name='адрес для доставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время заказа')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['firstname', 'lastname'], name='foodcartapp_firstna_b9b5f7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phonenumber'], name='foodcartapp_phonenu_5f4ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='foodcartapp_created_cd8d79_idx'),
        ),
    ]
