# Generated by Django 3.2.15 on 2022-12-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20221210_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Электронно'), ('CASH', 'Наличностью')], db_index=True, default='CARD', max_length=4, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESS', 'Обрабатывается'), ('COOKING', 'Готовится'), ('DELIVER', 'В доставке'), ('COMPLETE', 'Выполнен')], db_index=True, default='PROCESS', max_length=10, verbose_name='статус'),
        ),
    ]
