# Generated by Django 3.2.15 on 2023-01-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Обрабатывается'), (2, 'Готовится'), (3, 'В доставке'), (4, 'Выполнен')], db_index=True, default=1, verbose_name='статус'),
        ),
    ]
