# Generated by Django 3.2.15 on 2022-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='адрес')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='широта')),
                ('updated_at', models.DateTimeField(verbose_name='дата обновления')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'локации',
            },
        ),
    ]
